### ISSUE TITLE
Why not make an ssl jenkins as well?

### ISSUE THREAD

**Issue by Leopere** [MarvAmBass/docker-jenkins-docker#1]
I mean you already have this.
https://github.com/MarvAmBass/docker-nginx-ssl-secure

**Comment by MarvAmBass** [comment]
it's like comparing apples and oranges.

on one hand you have a stable widely spread webserver with good reverse proxy functionality

on the other hand you got a good build/deployment webapp

one team deals daily with prevention of attacks while the other one wants to create a usefull (maybe also a secure) webapp

as a operations guy i wouldn't recommend to use jenkins with direct internet connection.

mixing both containers, would be possible

BUT: not the docker way!!!! Much more work for zero benefit

Instead:

use jenkins docker container behind docker nginx ssl secure container
